name: 'Auto Approve PR'
description: 'Automatically approves a pull request'
author: 'yiwang-fever'

inputs:
  github-token:
    description: 'GitHub token with pull-requests write permission'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Approve Pull Request
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          await github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            event: 'APPROVE',
            body: 'Auto-approved by GitHub Action'
          })
